// src/components/qwik-react/pubsub.react.tsx
/** @jsxImportSource react */

import { useEffect, useState } from "react";
import { $counter1, $counter2 } from "../../store/nanostore";


export const ReactPublisher = () => {
  const [count, setCount] = useState($counter1.get());

  useEffect(() => {
    const unsubscribe = $counter1.subscribe((value) => {
      setCount(value);
    });
    return () => unsubscribe();
  });

  return (
    <>
      <h2>React publisher</h2>
      <button
        onClick={() => $counter1.set($counter1.get() + 1)}
      >
        <h2>click me: {count}</h2>
        {Math.random().toFixed(4)}
      </button>
    </>
  );
};


export const ReactSubscriber = () => {
  const [count, setCount] = useState($counter2.get());

  useEffect(() => {
    const unsubscribe = $counter2.subscribe((value) => {
      setCount(()=>value);
    });
    return () => unsubscribe();
  }, []);

  return (
    <div className="bordered">
      <h2>React subscriber</h2>
      <h3>count = {count}</h3>
      {Math.random().toFixed(4)}
    </div>
  );
};

// src/components/qwik-react/pubsub.qwik.tsx
/** @jsxImportSource @builder.io/qwik */

import { component$, useStore, useVisibleTask$ } from "@builder.io/qwik";
import { $counter1, $counter2 } from "../../store/nanostore";

export const QwikPublisher = component$(() => {
  const store = useStore({ count: $counter2.get() });

  useVisibleTask$(() => {
    const unsubscribe = $counter2.subscribe((value) => {
      store.count = value;
    });
    return () => unsubscribe();
  });

  return (
    <>
      <h2>Qwik publisher</h2>
      <button
        onClick$={() => $counter2.set($counter2.get() + 1)}
      >
        <h2>click me: {store.count}</h2>
        {Math.random().toFixed(4)}
      </button>
    </>
  );
});


export const QwikSubscriber = component$(() => {
  const store = useStore({ count: $counter1.get() });

  useVisibleTask$(() => {
    const unsubscribe = $counter1.subscribe((value) => {
      store.count = value;
    });
    return () => unsubscribe();
  });

  return (
    <div class="bordered">
      <h2>Qwik subscriber</h2>
      <h2>count = {store.count}</h2>
      {Math.random().toFixed(4)}
    </div>
  );
});
