// src/components/qwik/counter.qwik.tsx
/** @jsxImportSource @builder.io/qwik */

import { component$, useSignal, useTask$, useVisibleTask$ } from "@builder.io/qwik";
import { isServer } from "@builder.io/qwik/build";
 
export const Counter = component$(() => {
  const counter = useSignal(0);
  console.log("counter rendering");

  useTask$(() => {
    console.log("counter.useTask$");    
  });

  useTask$(({ track }) => {
    track(() => counter.value);
    if (isServer) return;
    console.log("counter.useTask$", counter.value); 
  });

  useVisibleTask$(() => {
    console.log("counter.useVisibleTask$", counter.value);    
  });

return <>
      <h2>This is a qwik counter</h2>
      <button onClick$={() => counter.value++}><h2>click me: {counter.value}</h2></button>
      <h2>{counter.value}</h2>
  </>;
});

// src/components/solid/Counter.solid.tsx
/** @jsxImportSource solid-js */
import { createSignal } from "solid-js";

export const Counter = () => {
  const [count, setCount] = createSignal(0);
  console.log("rendering solid counter");
  return (
    <div>
      <h1>Solid.js counter</h1>
      <p>Count: {count()}</p>
      <button onClick={() => setCount(c => c + 1)}>Increment</button>
    </div>
  );
};
